### ISSUE TITLE
input box doesn't close after clicking ok tick mark

### ISSUE THREAD

**Issue by SalahudinMalik** [aranta-rokade/Taxonomy-Editor-ng2-tree#1]
![del](https://user-images.githubusercontent.com/23012339/41720299-0a12cba0-757c-11e8-8dba-8fadf41d43f5.PNG)

**Comment by SalahudinMalik** [comment]
please let me know are you correcting it?

**Comment by aranta-rokade** [comment]
Thank you for bringing this up. As I am not actively working on this repository, I will fix this issue as time permits.

**Comment by SalahudinMalik** [comment]
I have added popup instead of text box. if you want I can create a merge request.

**Comment by aranta-rokade** [comment]
Please verify if [ab1621f](https://github.com/aranta-rokade/taxonomy-editor-tree/commit/ab1621f1a2264eff9f74a5ab2d9b7af7a4383026) fixes the issue.
